
const currentPath = (() => { const path = window.location.pathname.split('/').pop() || 'index.html'; return path === '' ? 'index.html' : path; })();
document.querySelectorAll('[data-nav]').forEach(link => { const href = link.getAttribute('href'); if (href === currentPath || (currentPath === 'index.html' && href === './')) link.classList.add('active'); });
const menu=document.querySelector('[data-mobile-menu]'),backdrop=document.querySelector('[data-backdrop]'),openBtn=document.querySelector('[data-menu-open]'),closeBtn=document.querySelector('[data-menu-close]');
function setMenu(open){ if(!menu||!backdrop)return; menu.classList.toggle('open',open); backdrop.classList.toggle('show',open); document.body.style.overflow=open?'hidden':''; }
openBtn?.addEventListener('click',()=>setMenu(true)); closeBtn?.addEventListener('click',()=>setMenu(false)); backdrop?.addEventListener('click',()=>setMenu(false)); document.querySelectorAll('[data-mobile-menu] a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));
const observer=new IntersectionObserver((entries)=>{ entries.forEach(entry=>{ if(entry.isIntersecting){ entry.target.classList.add('in-view'); observer.unobserve(entry.target);} }); },{threshold:0.12}); document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
function showToast(message,type='success'){ let stack=document.querySelector('.toast-stack'); if(!stack){ stack=document.createElement('div'); stack.className='toast-stack'; document.body.appendChild(stack);} const toast=document.createElement('div'); toast.className=`toast ${type==='error'?'error':''}`.trim(); toast.textContent=message; stack.appendChild(toast); setTimeout(()=>{ toast.style.opacity='0'; toast.style.transform='translateY(-8px)'; setTimeout(()=>toast.remove(),220); },2600); }
const form=document.querySelector('#contact-form'); if(form){ form.addEventListener('submit',(e)=>{ e.preventDefault(); const data=Object.fromEntries(new FormData(form).entries()); if(!data.name||!data.email||!data.nachricht){ showToast('Bitte füllen Sie alle Pflichtfelder aus','error'); return; } const emailRegex=/^[^\s@]+@[^\s@]+\.[^\s@]+$/; if(!emailRegex.test(data.email)){ showToast('Bitte geben Sie eine gültige E-Mail-Adresse ein','error'); return; } const btn=form.querySelector('button[type="submit"]'); const old=btn.innerHTML; btn.disabled=true; btn.innerHTML='<span>Senden…</span>'; setTimeout(()=>{ const submissions=JSON.parse(localStorage.getItem('concept34_submissions')||'[]'); submissions.push({...data,timestamp:new Date().toISOString(),id:Date.now()}); localStorage.setItem('concept34_submissions',JSON.stringify(submissions)); form.reset(); btn.disabled=false; btn.innerHTML=old; showToast('Ihre Anfrage wurde erfolgreich gespeichert'); },700); }); }
