window.CONCEPT34_SERVICES = [
  {
    slug: "abbruch-rueckbau",
    title: "Abbrucharbeiten | Rückbau aller Art",
    category: "rueckbau",
    categoryLabel: "Rückbau",
    image: "assets/img/projects/rueckbau-modern.jpg",
    gallery: ["assets/img/projects/rueckbau-modern.jpg", "assets/img/projects/entkernung-modern.jpg", "assets/img/projects/transport-modern.jpg"],
    summary: "Kontrollierter Rückbau von Gebäuden, Bauteilen und Flächen mit klarer Baustellenlogistik.",
    intro: "Wenn Bestand weichen muss, zählt ein ruhiger, geordneter Ablauf. Concept 34 plant den Rückbau so, dass Entsorgung, Materialtrennung und Folgegewerke sauber ineinandergreifen.",
    includes: ["Selektiver Rückbau und maschineller Abbruch", "Materialtrennung und Abtransport", "Vorbereitung für Neubau, Umbau oder Sanierung"],
    process: ["Besichtigung und Sicherung der Arbeitsbereiche", "Maschinen- und Containerlogistik planen", "Rückbau abschnittsweise ausführen", "Fläche sauber und begehbar übergeben"],
    perfectFor: ["Bestandsgebäude", "Garagen und Nebengebäude", "Umbauten", "Baufeldfreimachung"],
    metrics: ["Sauber getrennt", "Maschinell oder per Hand", "Übergabefertig"]
  },
  {
    slug: "entkernungen",
    title: "Entkernungen",
    category: "rueckbau",
    categoryLabel: "Rückbau",
    image: "assets/img/projects/entkernung-modern.jpg",
    gallery: ["assets/img/projects/entkernung-modern.jpg", "assets/img/projects/rueckbau-modern.jpg", "assets/img/projects/kernbohrung-modern.jpg"],
    summary: "Fachgerechte Innenrückbauten für Sanierung, Umbau und neue Raumkonzepte.",
    intro: "Bei Entkernungen bleibt die Struktur erhalten, während nicht benötigte Einbauten sauber entfernt werden. Das schafft klare Voraussetzungen für Planung, Ausbau und Sanierung.",
    includes: ["Entfernung von Decken, Böden und Leichtbauwänden", "Rückbau von Installationen nach Abstimmung", "Sortierte Bereitstellung und Entsorgung"],
    process: ["Bestand prüfen und Schutzbereiche definieren", "Demontagefolge festlegen", "Material kontrolliert ausbauen", "Innenbereich besenrein übergeben"],
    perfectFor: ["Wohnungen", "Büroflächen", "Ladenbau", "Sanierungsobjekte"],
    metrics: ["Innen sauber", "Struktur erhalten", "Ausbau bereit"]
  },
  {
    slug: "haushaltsaufloesung-entruempelung",
    title: "Haushaltsauflösung | Entrümpelung",
    category: "rueckbau",
    categoryLabel: "Rückbau",
    image: "assets/img/projects/entkernung-modern.jpg",
    gallery: ["assets/img/projects/entkernung-modern.jpg", "assets/img/projects/transport-modern.jpg", "assets/img/projects/rueckbau-modern.jpg"],
    summary: "Komplette Räumung von Wohnungen, Häusern, Kellern und Nebenflächen inklusive Abtransport.",
    intro: "Eine gute Entrümpelung nimmt Druck aus einem Projekt. Räume werden strukturiert geräumt, verwertbare Materialien getrennt und die Fläche für den nächsten Schritt vorbereitet.",
    includes: ["Räumung von Wohn- und Nebenräumen", "Sortierung, Trennung und Abtransport", "Übergabe nach vereinbartem Zustand"],
    process: ["Umfang und Zugänge aufnehmen", "Container und Transport abstimmen", "Räumung geordnet durchführen", "Flächen kontrollieren und übergeben"],
    perfectFor: ["Wohnungsauflösungen", "Keller und Dachböden", "Objektvorbereitung", "Nachlassimmobilien"],
    metrics: ["Diskret", "Strukturiert", "Terminsicher"]
  },
  {
    slug: "schadstoff-sanierung",
    title: "Schadstoff Sanierung",
    category: "rueckbau",
    categoryLabel: "Rückbau",
    image: "assets/img/projects/entkernung-modern.jpg",
    gallery: ["assets/img/projects/entkernung-modern.jpg", "assets/img/projects/rueckbau-modern.jpg", "assets/img/projects/kernbohrung-modern.jpg"],
    summary: "Koordinierte Vorbereitung und sichere Abläufe bei belasteten Bauteilen und Materialien.",
    intro: "Bei möglichen Schadstoffen braucht es Sorgfalt, Abstimmung und klare Schutzmaßnahmen. Concept 34 unterstützt bei der praktischen Umsetzung und koordiniert die nötigen Arbeitsschritte zuverlässig.",
    includes: ["Sicherung betroffener Bereiche nach Vorgabe", "Separierte Aufnahme belasteter Materialien", "Abstimmung von Entsorgungswegen"],
    process: ["Befundlage und Schutzbedarf klären", "Arbeitsbereich vorbereiten", "Material getrennt aufnehmen", "Dokumentierte Übergabe herstellen"],
    perfectFor: ["Sanierungsobjekte", "Altbauten", "Innenrückbau", "Umbauvorbereitung"],
    metrics: ["Sorgfältig", "Abgestimmt", "Dokumentiert"]
  },
  {
    slug: "stemmarbeiten",
    title: "Stemmarbeiten per Hand und Maschine",
    category: "rueckbau",
    categoryLabel: "Rückbau",
    image: "assets/img/projects/kernbohrung-modern.jpg",
    gallery: ["assets/img/projects/kernbohrung-modern.jpg", "assets/img/projects/entkernung-modern.jpg", "assets/img/projects/rueckbau-modern.jpg"],
    summary: "Präzise Stemmarbeiten für Öffnungen, Schlitze, Rückbau und bauliche Anpassungen.",
    intro: "Stemmarbeiten müssen kraftvoll und gleichzeitig kontrolliert sein. Mit passender Maschine, sauberer Vorbereitung und Staubschutz entstehen klare Ergebnisse ohne unnötige Folgeschäden.",
    includes: ["Hand- und Maschinenstemmen", "Schlitze, Aussparungen und Teilrückbau", "Vorbereitung für Folgegewerke"],
    process: ["Bauteil und Zielmaß prüfen", "Umfeld schützen", "Stemmarbeiten kontrolliert ausführen", "Schutt aufnehmen und Bereich reinigen"],
    perfectFor: ["Umbauten", "Installationswege", "Bad- und Küchensanierung", "Wandöffnungen"],
    metrics: ["Präzise", "Kontrolliert", "Sauber"]
  },
  {
    slug: "kernbohrungen",
    title: "Kernbohrungen",
    category: "tiefbau",
    categoryLabel: "Tiefbau",
    image: "assets/img/projects/kernbohrung-modern.jpg",
    gallery: ["assets/img/projects/kernbohrung-modern.jpg", "assets/img/projects/entwaesserung-modern.jpg", "assets/img/projects/entkernung-modern.jpg"],
    summary: "Saubere Bohrungen in Beton und Mauerwerk für Leitungen, Lüftung und Durchführungen.",
    intro: "Kernbohrungen schaffen exakte Öffnungen mit sauberem Randbild. Sie sind ideal, wenn Leitungen, Rohre oder technische Durchführungen präzise gesetzt werden müssen.",
    includes: ["Bohrungen in Beton und Mauerwerk", "Staub- und Wassermanagement", "Vorbereitung für Rohr- und Leitungsdurchführungen"],
    process: ["Bohrpunkt und Durchmesser abstimmen", "Bohrgerät sicher einrichten", "Kernbohrung ausführen", "Bohrkern und Arbeitsbereich aufnehmen"],
    perfectFor: ["Lüftung", "Entwässerung", "Hausanschlüsse", "Technische Installationen"],
    metrics: ["Exakt", "Sauberes Schnittbild", "Planbar"]
  },
  {
    slug: "durchbrueche",
    title: "Durchbrüche",
    category: "rueckbau",
    categoryLabel: "Rückbau",
    image: "assets/img/projects/kernbohrung-modern.jpg",
    gallery: ["assets/img/projects/kernbohrung-modern.jpg", "assets/img/projects/entkernung-modern.jpg", "assets/img/projects/rueckbau-modern.jpg"],
    summary: "Fachgerechte Wand- und Deckendurchbrüche für Türen, Fenster, Leitungen und neue Grundrisse.",
    intro: "Durchbrüche verändern Räume spürbar. Wichtig sind saubere Kanten, abgestimmte Sicherung und eine Ausführung, die Folgearbeiten erleichtert.",
    includes: ["Wandöffnungen und Leitungsdurchbrüche", "Vorbereitung und Randbearbeitung", "Schuttaufnahme und Übergabe"],
    process: ["Maße und Statikvorgaben prüfen", "Arbeitsbereich sichern", "Durchbruch herstellen", "Kanten und Fläche übergeben"],
    perfectFor: ["Türöffnungen", "Fensteröffnungen", "Leitungsführung", "Innenumbau"],
    metrics: ["Maßgenau", "Abgestimmt", "Folgewerk bereit"]
  },
  {
    slug: "montage-demontage",
    title: "Montage | Demontage Arbeiten",
    category: "service",
    categoryLabel: "Service",
    image: "assets/img/projects/transport-modern.jpg",
    gallery: ["assets/img/projects/transport-modern.jpg", "assets/img/projects/entkernung-modern.jpg", "assets/img/projects/aussenanlage-modern.jpg"],
    summary: "Montage- und Demontagehilfe für Bauteile, Einrichtungen, Anlagen und Baustellenlogistik.",
    intro: "Manche Projekte brauchen nicht nur Maschinen, sondern Hände, Struktur und Erfahrung. Concept 34 übernimmt Montage- und Demontagearbeiten dort, wo saubere Vorbereitung zählt.",
    includes: ["Demontage von Bauteilen und Einbauten", "Montageunterstützung nach Absprache", "Transport- und Baustellenkoordination"],
    process: ["Bauteile aufnehmen", "Werkzeug und Transport vorbereiten", "Demontage oder Montage durchführen", "Material geordnet übergeben"],
    perfectFor: ["Umbauten", "Gewerbeflächen", "Baustellenvorbereitung", "Einzelmaßnahmen"],
    metrics: ["Flexibel", "Geordnet", "Praxisnah"]
  },
  {
    slug: "betonarbeiten",
    title: "Beton Arbeiten",
    category: "tiefbau",
    categoryLabel: "Tiefbau",
    image: "assets/img/projects/kernbohrung-modern.jpg",
    gallery: ["assets/img/projects/kernbohrung-modern.jpg", "assets/img/projects/entwaesserung-modern.jpg", "assets/img/projects/aussenanlage-modern.jpg"],
    summary: "Betonarbeiten für Fundamente, kleine Flächen, Unterbauten und bauliche Ergänzungen.",
    intro: "Solide Betonarbeiten sind die Grundlage für tragfähige Bauteile. Vom Unterbau bis zur kleinen Ergänzung geht es um Vorbereitung, Schalung, Verdichtung und saubere Übergänge.",
    includes: ["Kleine Fundamente und Betonflächen", "Vorbereitung von Untergründen", "Schalungs- und Ergänzungsarbeiten"],
    process: ["Untergrund vorbereiten", "Schalung und Höhen klären", "Beton fachgerecht einbringen", "Nacharbeiten und Übergabe"],
    perfectFor: ["Fundamente", "Randbereiche", "Außenflächen", "Sanierungsergänzungen"],
    metrics: ["Tragfähig", "Sauber vorbereitet", "Langlebig"]
  },
  {
    slug: "baggerarbeiten",
    title: "Bagger Arbeiten aller Art",
    category: "tiefbau",
    categoryLabel: "Tiefbau",
    image: "assets/img/projects/entwaesserung-modern.jpg",
    gallery: ["assets/img/projects/entwaesserung-modern.jpg", "assets/img/projects/transport-modern.jpg", "assets/img/projects/aussenanlage-modern.jpg"],
    summary: "Aushub, Erdbewegung, Planum und Vorbereitung für Außenanlagen, Leitungen und Fundamente.",
    intro: "Baggerarbeiten bringen Struktur in das Gelände. Mit passender Maschine und sauberer Planung entstehen Flächen, Gräben und Untergründe, die für den nächsten Schritt bereit sind.",
    includes: ["Aushub und Erdbewegung", "Planum und Unterbauvorbereitung", "Materialaufnahme und Abtransport"],
    process: ["Gelände und Zufahrt prüfen", "Aushub und Höhen festlegen", "Baggerarbeiten ausführen", "Untergrund profilieren und übergeben"],
    perfectFor: ["Gärten", "Einfahrten", "Leitungsgräben", "Fundamente"],
    metrics: ["Präzise Höhen", "Passende Maschine", "Schnell vorbereitet"]
  },
  {
    slug: "aussenanlagen",
    title: "Gestaltung von Außenanlagen",
    category: "aussen",
    categoryLabel: "Außenanlagen",
    image: "assets/img/projects/aussenanlage-modern.jpg",
    gallery: ["assets/img/projects/aussenanlage-modern.jpg", "assets/img/projects/vorher-nachher-aussenanlage.jpg", "assets/img/projects/pool-zaun-modern.jpg"],
    summary: "Außenbereiche planen und herstellen: Wege, Zufahrten, Flächen, Kanten und Übergänge.",
    intro: "Eine gute Außenanlage wirkt ruhig, weil Unterbau, Entwässerung und Oberfläche zusammenspielen. Concept 34 verbindet praktische Ausführung mit sauberem, modernem Erscheinungsbild.",
    includes: ["Vorbereitung von Flächen und Unterbau", "Wege, Zufahrten und Terrassenbereiche", "Randsteine, Kanten und Übergänge"],
    process: ["Nutzung und Gestaltung klären", "Unterbau und Entwässerung planen", "Flächen herstellen", "Kanten sauber abschließen"],
    perfectFor: ["Einfahrten", "Gartenwege", "Terrassenumfeld", "Eingangsbereiche"],
    metrics: ["Modern", "Robust", "Alltagstauglich"]
  },
  {
    slug: "baumfaellungen",
    title: "Baumfällungen",
    category: "aussen",
    categoryLabel: "Außenanlagen",
    image: "assets/img/projects/gruenarbeiten-modern.jpg",
    gallery: ["assets/img/projects/gruenarbeiten-modern.jpg", "assets/img/projects/transport-modern.jpg", "assets/img/projects/aussenanlage-modern.jpg"],
    summary: "Sichere Baumfällungen und vorbereitende Arbeiten für freie, neu nutzbare Außenflächen.",
    intro: "Baumfällungen brauchen Umsicht und Ordnung. Das Umfeld wird geschützt, Schnittgut geordnet aufgenommen und die Fläche für die weitere Nutzung vorbereitet.",
    includes: ["Fällarbeiten nach Abstimmung", "Schnittgutaufnahme und Abtransport", "Vorbereitung für neue Außenflächen"],
    process: ["Baum und Umfeld prüfen", "Sicherheitsbereich festlegen", "Fällung und Zerkleinerung durchführen", "Schnittgut und Fläche übergeben"],
    perfectFor: ["Privatgärten", "Baufeldfreimachung", "Zufahrten", "Grundstückspflege"],
    metrics: ["Sicher", "Aufgeräumt", "Fläche frei"]
  },
  {
    slug: "gruenschnitt",
    title: "Grünschnitt",
    category: "aussen",
    categoryLabel: "Außenanlagen",
    image: "assets/img/projects/gruenarbeiten-modern.jpg",
    gallery: ["assets/img/projects/gruenarbeiten-modern.jpg", "assets/img/projects/aussenanlage-modern.jpg", "assets/img/projects/pool-zaun-modern.jpg"],
    summary: "Pflege, Rückschnitt und Beräumung von Grünflächen als Vorbereitung oder laufender Service.",
    intro: "Grünschnitt sorgt dafür, dass Grundstücke gepflegt und nutzbar bleiben. Besonders vor Bau- oder Außenarbeiten schafft er freie Sicht und saubere Arbeitsflächen.",
    includes: ["Rückschnitt von Hecken und Sträuchern", "Aufnahme und Abtransport von Grünmaterial", "Vorbereitung für Garten- und Bauarbeiten"],
    process: ["Flächen und Pflanzenbestand ansehen", "Schnittumfang abstimmen", "Grünarbeiten durchführen", "Material abfahren und Fläche reinigen"],
    perfectFor: ["Gärten", "Grundstücke", "Zufahrten", "Vorbereitung für Außenanlagen"],
    metrics: ["Gepflegt", "Schnell", "Ordentlich"]
  },
  {
    slug: "pflasterarbeiten",
    title: "Pflaster Arbeiten",
    category: "aussen",
    categoryLabel: "Außenanlagen",
    image: "assets/img/projects/aussenanlage-modern.jpg",
    gallery: ["assets/img/projects/aussenanlage-modern.jpg", "assets/img/projects/vorher-nachher-aussenanlage.jpg", "assets/img/projects/entwaesserung-modern.jpg"],
    summary: "Pflasterflächen, Platten, Randsteine und saubere Kanten für Einfahrten, Wege und Höfe.",
    intro: "Pflasterarbeiten wirken erst hochwertig, wenn der Unterbau stimmt. Concept 34 achtet auf Tragfähigkeit, Entwässerung, Linienführung und ein sauberes Fugenbild.",
    includes: ["Unterbau und Tragschichten", "Pflaster- und Plattenverlegung", "Randsteine, Rinnen und Kanten"],
    process: ["Höhen und Gefälle festlegen", "Unterbau herstellen", "Pflaster sauber verlegen", "Abrütteln, verfugen und übergeben"],
    perfectFor: ["Einfahrten", "Wege", "Terrassen", "Hofflächen"],
    metrics: ["Belastbar", "Saubere Linien", "Wertiger Eindruck"]
  },
  {
    slug: "poolarbeiten",
    title: "Pool Arbeiten",
    category: "aussen",
    categoryLabel: "Außenanlagen",
    image: "assets/img/projects/pool-zaun-modern.jpg",
    gallery: ["assets/img/projects/pool-zaun-modern.jpg", "assets/img/projects/entwaesserung-modern.jpg", "assets/img/projects/aussenanlage-modern.jpg"],
    summary: "Vorbereitende Erd-, Unterbau- und Umfeldarbeiten rund um Poolprojekte.",
    intro: "Poolarbeiten verbinden Erdarbeiten, Unterbau und saubere Außenflächen. Concept 34 schafft die praktische Grundlage, damit Becken, Technik und Umfeld später stimmig zusammenpassen.",
    includes: ["Aushub und Vorbereitung des Poolbereichs", "Unterbau, Kiesbett und Randbereiche", "Umfeldarbeiten und Materiallogistik"],
    process: ["Poolposition und Höhen prüfen", "Aushub herstellen", "Unterbau vorbereiten", "Umfeld für Folgegewerke übergeben"],
    perfectFor: ["Gartenpools", "Poolumfelder", "Technikbereiche", "Außenanlagen"],
    metrics: ["Passgenau", "Gut vorbereitet", "Sauberes Umfeld"]
  },
  {
    slug: "zaunanlagen",
    title: "Zaunanlagen",
    category: "aussen",
    categoryLabel: "Außenanlagen",
    image: "assets/img/projects/pool-zaun-modern.jpg",
    gallery: ["assets/img/projects/pool-zaun-modern.jpg", "assets/img/projects/aussenanlage-modern.jpg", "assets/img/projects/gruenarbeiten-modern.jpg"],
    summary: "Zaunlinien, Pfosten, Fundamente und Anschlüsse für klare Grundstücksgrenzen.",
    intro: "Ein Zaun soll schützen, strukturieren und optisch passen. Wichtig sind gerade Linien, stabile Fundamente und sauber gelöste Anschlüsse an Bestand und Gelände.",
    includes: ["Vorbereitung der Zauntrasse", "Pfosten- und Fundamentarbeiten", "Montageunterstützung und Anschlussdetails"],
    process: ["Linienführung und Höhen prüfen", "Fundamentpunkte vorbereiten", "Zaunelemente setzen", "Fläche und Anschlüsse nacharbeiten"],
    perfectFor: ["Privatgrundstücke", "Gärten", "Einfahrten", "Poolbereiche"],
    metrics: ["Gerade Linie", "Stabil", "Sauber integriert"]
  },
  {
    slug: "entwaesserung-kanalbau",
    title: "Entwässerung | Kanalbau",
    category: "tiefbau",
    categoryLabel: "Tiefbau",
    image: "assets/img/projects/entwaesserung-modern.jpg",
    gallery: ["assets/img/projects/entwaesserung-modern.jpg", "assets/img/projects/kernbohrung-modern.jpg", "assets/img/projects/aussenanlage-modern.jpg"],
    summary: "Drainage, Entwässerungsrinnen, Leitungsgräben und Kanalanschlüsse sauber vorbereitet.",
    intro: "Wasser muss zuverlässig geführt werden. Concept 34 bereitet Entwässerungen so vor, dass Gefälle, Bettung, Anschluss und Oberfläche zusammenpassen.",
    includes: ["Leitungsgräben und Rohrbettung", "Drainage und Entwässerungsrinnen", "Vorbereitung von Kanalanschlüssen"],
    process: ["Gefälle und Anschluss klären", "Graben und Bettung herstellen", "Rohrführung vorbereiten", "Verdichten und Oberfläche übergeben"],
    perfectFor: ["Einfahrten", "Hofflächen", "Hausanschlüsse", "Gartenentwässerung"],
    metrics: ["Richtiges Gefälle", "Sauber gebettet", "Dicht vorbereitet"]
  },
  {
    slug: "raumgestaltung",
    title: "Raumgestaltung",
    category: "service",
    categoryLabel: "Service",
    image: "assets/img/projects/entkernung-modern.jpg",
    gallery: ["assets/img/projects/entkernung-modern.jpg", "assets/img/projects/kernbohrung-modern.jpg", "assets/img/projects/aussenanlage-modern.jpg"],
    summary: "Praktische Vorbereitung und bauliche Anpassungen für neue Raumwirkung.",
    intro: "Raumgestaltung beginnt oft mit sauberer Vorbereitung: Rückbau, Öffnungen, Flächen, Untergründe und Details. Concept 34 schafft die Basis, auf der Ausbau und Gestaltung aufbauen.",
    includes: ["Vorbereitende Rückbauarbeiten", "Öffnungen und Anpassungen", "Saubere Übergabe an Folgegewerke"],
    process: ["Zielbild und Bestand aufnehmen", "Rückbau und Anpassungen planen", "Arbeiten sauber ausführen", "Flächen für Ausbau übergeben"],
    perfectFor: ["Wohnräume", "Gewerbeflächen", "Umbauten", "Sanierungen"],
    metrics: ["Vorbereitet", "Flexibel", "Ausbaufähig"]
  },
  {
    slug: "kleinmaschinen-transport",
    title: "Kleinmaschinen Transport bis 3t",
    category: "service",
    categoryLabel: "Service",
    image: "assets/img/projects/transport-modern.jpg",
    gallery: ["assets/img/projects/transport-modern.jpg", "assets/img/projects/entwaesserung-modern.jpg", "assets/img/projects/aussenanlage-modern.jpg"],
    summary: "Transport von kompakten Maschinen und Geräten für flexible Baustellenlogistik.",
    intro: "Gute Baustellenlogistik spart Zeit. Concept 34 unterstützt mit Transporten von Kleinmaschinen bis 3t und sorgt dafür, dass Gerät und Material dort ankommen, wo sie gebraucht werden.",
    includes: ["Transport kleiner Maschinen und Geräte", "Sicherung und Baustellenabstimmung", "Unterstützung bei Gerätewechsel und Logistik"],
    process: ["Transportgut und Zufahrt prüfen", "Ladung sichern", "Transport durchführen", "Maschine vor Ort positionieren"],
    perfectFor: ["Minibagger", "Kompaktlader", "Baustellengeräte", "Kurzfristige Einsätze"],
    metrics: ["Bis 3t", "Flexibel", "Direkt vor Ort"]
  }
];
